# Database configuration
spring:
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/recipify_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

# API documentation configuration
springdoc:
  show-actuator: true
  packagesToScan: com.recipify.recipify
  pathsToMatch: /**
  swagger-ui:
    operationsSorter: method
    path: /


# Hunter API configuration
hunter-api:
  url: https://api.hunter.io/v2/email-verifier
  api-key: your_api_key_here


# Clearbit API configuration
clearbit-api:
  url: https://person.clearbit.com/v2/people/find
  api-key: your_api_key_here
